import type { Language } from "./types";

const copy = {
  pt: {
    setupEyebrow: "CONFIGURAÇÃO DO ESTUDO",
    setupTitle: "Antes de abrir a sala de concepção",
    setupLead: "Defina como este estudo deve pensar. Você ainda não está escolhendo a solução da missão.",
    projectName: "Nome do projeto",
    projectNamePlaceholder: "Ex. Aurora",
    studyIntent: "Qual é a natureza do estudo?",
    intentProblem: "Resolver um problema",
    intentProblemDesc: "A missão nasce de uma necessidade que precisa ser entendida antes de propor uma solução.",
    intentTechnology: "Demonstrar uma tecnologia",
    intentTechnologyDesc: "O estudo precisa provar uma capacidade ou reduzir incerteza tecnológica em ambiente relevante.",
    intentScience: "Ciência ou exploração",
    intentScienceDesc: "O estudo parte de uma pergunta, fenômeno ou oportunidade de observação.",
    intentOpen: "Exploração aberta",
    intentOpenDesc: "Ainda não existe uma direção forte. A sala deve ajudar a descobrir caminhos antes de consolidar o problema.",
    startingStatement: "Ponto de partida",
    startingStatementHint: "Escreva só o que motivou o estudo. Isso não vira uma descrição formal da missão.",
    startingStatementPlaceholder: "Ex. Quero reduzir o tempo para identificar novos focos de incêndio em grandes áreas florestais.",
    framework: "Como a missão será considerada definida?",
    frameworkStandard: "Estrutura padrão Mission Dev",
    frameworkStandardDesc: "Usa critérios de definição de missão inicial e exige evidência no mapa antes de validar uma fase.",
    frameworkCustom: "Estrutura personalizada",
    frameworkCustomDesc: "Começa com a mesma base, mas permite substituir ou criar critérios específicos para este projeto.",
    references: "Referências do projeto",
    referencesHint: "Registre padrões, templates ou documentos que devem orientar as decisões. Eles passam a fazer parte da configuração exportável.",
    referencePlaceholder: "Ex. ECSS tailoring, requisito interno, template da organização...",
    addReference: "Adicionar referência",
    noReferences: "Nenhuma referência adicionada.",
    binding: "Vinculante",
    referenceOnly: "Referência",
    remove: "Remover",
    backHome: "Voltar ao início",
    enterRoom: "Abrir sala de concepção",
    setupSaved: "Essa configuração será salva dentro do projeto e usada como contexto do restante da missão.",
    currentMap: "Mapa atual",
    globalMap: "Visão macro",
    pageProgress: "Progresso desta página",
    projectProgress: "Progresso da missão",
    files: "Arquivos do projeto",
    studies: "Estudos",
    closePanel: "Fechar painel",
    freeIdeas: "Ideias livres",
    openQuestions: "Perguntas em aberto",
    moveToIdeas: "Mover para ideias livres",
    moveToQuestions: "Mover para perguntas em aberto",
    moveToMain: "Mover para estrutura principal",
    exploreIssue: "Abrir estudo",
    issueStudy: "ESTUDO DE INCONSISTÊNCIA",
    issueStudyDraft: "Draft de análise",
    issueEvidence: "Elementos envolvidos",
    issueHypotheses: "Hipóteses de resolução",
    studyNotes: "Notas do estudo",
    studyNotesPlaceholder: "Registre observações, trade-offs, dados que faltam e o motivo das decisões...",
    addHypothesis: "Nova hipótese",
    hypothesisPlaceholder: "Escreva uma hipótese de resolução sem alterar o mapa principal.",
    favor: "Priorizar",
    reject: "Descartar",
    candidate: "Candidata",
    favored: "Prioritária",
    rejected: "Descartada",
    adoptConclusion: "Adotar como conclusão",
    conclusionHelp: "Adotar uma conclusão resolve a inconsistência no projeto sem criar automaticamente outro card no mapa macro.",
    studyResolved: "Estudo resolvido",
    reopenStudy: "Reabrir estudo",
    scopedIssues: "As inconsistências mostradas aqui pertencem somente ao mapa que está aberto.",
    noScopedIssues: "Nenhuma inconsistência neste mapa.",
    standardProgress: "Padrão",
    customProgress: "Personalizado",
    progressModel: "Modelo de progresso",
    standardProgressDesc: "Critérios base para concepção inicial de missão.",
    customProgressDesc: "Critérios definidos pelo próprio projeto e ligados a evidências do mapa.",
    customCriteria: "Critérios personalizados",
    addCriterionFromSelected: "Criar critério com o card selecionado",
    selectCardForCriterion: "Selecione um card no mapa para usá-lo como evidência de um novo critério.",
    criterionName: "Nome do critério",
    criterionPlaceholder: "Ex. Critério operacional validado",
    mandatory: "Obrigatório",
    optional: "Opcional",
    removeCriterion: "Remover critério",
    criterionEvidence: "Evidência",
    standardCriteria: "Critérios padrão",
    pageStateProgress: "Quando você entra em uma página específica, este indicador mostra a maturidade apenas dos elementos visíveis nela.",
    cannotClose: "A fase só pode ser validada quando todos os critérios obrigatórios têm evidência definida e não existem inconsistências críticas abertas.",
    validatePhase: "Validar fase Problema",
    validatedPhase: "Fase Problema validada",
    projectFiles: "ARQUIVOS DO PROJETO",
    autosaved: "Salvo automaticamente neste navegador",
    exportProject: "Exportar projeto",
    exportHint: "O arquivo .mission.json contém configuração, mapa, critérios, estudos e templates aplicados.",
    fileStudy: "Configuração do estudo",
    fileProgress: "Modelo de progresso",
    fileBoard: "Mapa da fase Problema",
    fileStudies: "Drafts de inconsistências",
    fileTemplate: "Template ativo",
    projectStructure: "Estrutura persistente",
    openAsPage: "Abrir como página",
    organizeTopDown: "Organizar de cima para baixo",
    cardMenu: "Opções do card",
    edit: "Editar",
    connect: "Conectar",
    deleteConnection: "Excluir conexão",
    connectionSelected: "Conexão selecionada",
    newIdea: "+ Nova ideia",
    editCard: "EDITAR CARD",
    newCard: "NOVO CARD",
    cardText: "Texto do card",
    cardWords: "Máximo de 24 palavras.",
    saveCard: "Salvar card",
    cancel: "Cancelar",
    close: "Fechar",
    back: "Voltar",
    zoomIn: "Aumentar zoom",
    zoomOut: "Diminuir zoom",
    fit: "Enquadrar mapa",
    organize: "Organizar",
    problemPhase: "02 · PROBLEMA",
    conceptionRoom: "SALA DE CONCEPÇÃO",
    dragHint: "arraste cards · arraste o fundo · conecte pelos pontos · use zoom",
    projectNameDefault: "Nova missão",
    standardTemplate: "Mission Dev Core v1",
    filesPanelDescription: "A interface mostra a mesma separação lógica que poderá ser persistida por um backend ou distribuída em templates no futuro.",
    templateLocked: "Templates futuros poderão bloquear partes desta configuração e liberar somente os campos permitidos pelo projeto.",
    noCustomCriteria: "Nenhum critério personalizado ainda.",
    currentScope: "Escopo atual",
    macroScope: "Missão completa",
    openStudyFromIssue: "Explore a inconsistência em um draft separado antes de decidir se algo deve voltar para o mapa principal.",
    resolvedStudies: "Estudos resolvidos",
    draftStudies: "Drafts abertos",
    noStudies: "Nenhum estudo de inconsistência criado ainda."
  },
  en: {
    setupEyebrow: "STUDY SETUP",
    setupTitle: "Before opening the conception room",
    setupLead: "Define how this study should think. You are not choosing the mission solution yet.",
    projectName: "Project name",
    projectNamePlaceholder: "E.g. Aurora",
    studyIntent: "What kind of study is this?",
    intentProblem: "Solve a problem",
    intentProblemDesc: "The mission starts from a need that must be understood before a solution is proposed.",
    intentTechnology: "Demonstrate a technology",
    intentTechnologyDesc: "The study must prove a capability or reduce technology uncertainty in a relevant environment.",
    intentScience: "Science or exploration",
    intentScienceDesc: "The study starts from a question, phenomenon, or observation opportunity.",
    intentOpen: "Open exploration",
    intentOpenDesc: "There is no strong direction yet. The room should help discover paths before the problem is consolidated.",
    startingStatement: "Starting point",
    startingStatementHint: "Write only what motivated the study. This is not treated as a formal mission description.",
    startingStatementPlaceholder: "E.g. I want to reduce the time needed to identify new wildfire outbreaks across large forest areas.",
    framework: "How will the mission be considered defined?",
    frameworkStandard: "Mission Dev standard framework",
    frameworkStandardDesc: "Uses early mission-definition criteria and requires map evidence before a phase can be validated.",
    frameworkCustom: "Custom framework",
    frameworkCustomDesc: "Starts from the same baseline but allows project-specific criteria to replace or extend it.",
    references: "Project references",
    referencesHint: "Register standards, templates, or documents that should guide decisions. They become part of the exportable project configuration.",
    referencePlaceholder: "E.g. ECSS tailoring, internal requirement, organization template...",
    addReference: "Add reference",
    noReferences: "No references added.",
    binding: "Binding",
    referenceOnly: "Reference",
    remove: "Remove",
    backHome: "Back to home",
    enterRoom: "Open conception room",
    setupSaved: "This setup is stored inside the project and used as context for the rest of the mission.",
    currentMap: "Current map",
    globalMap: "Macro view",
    pageProgress: "Page progress",
    projectProgress: "Mission progress",
    files: "Project files",
    studies: "Studies",
    closePanel: "Close panel",
    freeIdeas: "Free ideas",
    openQuestions: "Open questions",
    moveToIdeas: "Move to free ideas",
    moveToQuestions: "Move to open questions",
    moveToMain: "Move to main structure",
    exploreIssue: "Open study",
    issueStudy: "INCONSISTENCY STUDY",
    issueStudyDraft: "Analysis draft",
    issueEvidence: "Elements involved",
    issueHypotheses: "Resolution hypotheses",
    studyNotes: "Study notes",
    studyNotesPlaceholder: "Record observations, trade-offs, missing data, and the reasoning behind decisions...",
    addHypothesis: "New hypothesis",
    hypothesisPlaceholder: "Write a resolution hypothesis without changing the main map.",
    favor: "Prioritize",
    reject: "Reject",
    candidate: "Candidate",
    favored: "Favored",
    rejected: "Rejected",
    adoptConclusion: "Adopt as conclusion",
    conclusionHelp: "Adopting a conclusion resolves the inconsistency in the project without automatically creating another card on the macro map.",
    studyResolved: "Study resolved",
    reopenStudy: "Reopen study",
    scopedIssues: "The inconsistencies shown here belong only to the map currently open.",
    noScopedIssues: "No inconsistencies in this map.",
    standardProgress: "Standard",
    customProgress: "Custom",
    progressModel: "Progress model",
    standardProgressDesc: "Baseline criteria for early mission conception.",
    customProgressDesc: "Project-defined criteria linked to evidence in the map.",
    customCriteria: "Custom criteria",
    addCriterionFromSelected: "Create criterion from selected card",
    selectCardForCriterion: "Select a card in the map to use it as evidence for a new criterion.",
    criterionName: "Criterion name",
    criterionPlaceholder: "E.g. Operational criterion validated",
    mandatory: "Mandatory",
    optional: "Optional",
    removeCriterion: "Remove criterion",
    criterionEvidence: "Evidence",
    standardCriteria: "Standard criteria",
    pageStateProgress: "When you enter a focused page, this indicator shows the maturity of only the elements visible there.",
    cannotClose: "The phase can only be validated when all mandatory criteria have defined evidence and no critical inconsistencies remain open.",
    validatePhase: "Validate Problem phase",
    validatedPhase: "Problem phase validated",
    projectFiles: "PROJECT FILES",
    autosaved: "Automatically saved in this browser",
    exportProject: "Export project",
    exportHint: "The .mission.json file contains configuration, graph, criteria, studies, and applied templates.",
    fileStudy: "Study configuration",
    fileProgress: "Progress model",
    fileBoard: "Problem phase map",
    fileStudies: "Inconsistency drafts",
    fileTemplate: "Active template",
    projectStructure: "Persistent structure",
    openAsPage: "Open as page",
    organizeTopDown: "Organize top to bottom",
    cardMenu: "Card options",
    edit: "Edit",
    connect: "Connect",
    deleteConnection: "Delete connection",
    connectionSelected: "Connection selected",
    newIdea: "+ New idea",
    editCard: "EDIT CARD",
    newCard: "NEW CARD",
    cardText: "Card text",
    cardWords: "Maximum of 24 words.",
    saveCard: "Save card",
    cancel: "Cancel",
    close: "Close",
    back: "Back",
    zoomIn: "Zoom in",
    zoomOut: "Zoom out",
    fit: "Fit map",
    organize: "Organize",
    problemPhase: "02 · PROBLEM",
    conceptionRoom: "CONCEPTION ROOM",
    dragHint: "drag cards · drag the background · connect from handles · use zoom",
    projectNameDefault: "New mission",
    standardTemplate: "Mission Dev Core v1",
    filesPanelDescription: "The interface exposes the same logical separation that can later be persisted by a backend or distributed through templates.",
    templateLocked: "Future templates can lock parts of this configuration and expose only the fields a project is allowed to change.",
    noCustomCriteria: "No custom criteria yet.",
    currentScope: "Current scope",
    macroScope: "Complete mission",
    openStudyFromIssue: "Explore the inconsistency in a separate draft before deciding whether anything should return to the main map.",
    resolvedStudies: "Resolved studies",
    draftStudies: "Open drafts",
    noStudies: "No inconsistency studies have been created yet."
  }
} as const;

export type UxCopyKey = keyof typeof copy.pt;

export function ux(language: Language, key: UxCopyKey): string {
  return copy[language][key];
}
